CREATE DATABASE IF NOT EXISTS dormitory_system DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE dormitory_system;

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(40) UNIQUE NOT NULL,
  password VARCHAR(80) NOT NULL,
  real_name VARCHAR(60) NOT NULL,
  role VARCHAR(20) NOT NULL,
  phone VARCHAR(30),
  room_no VARCHAR(30),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS biz_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  category VARCHAR(40) NOT NULL,
  title VARCHAR(120) NOT NULL,
  owner VARCHAR(60),
  location VARCHAR(80),
  amount DECIMAL(10,2) DEFAULT 0,
  status VARCHAR(30) NOT NULL,
  content TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
